import { Bike } from "src/app/models/types/bike";

export const sampleBikes: Bike[] = [
    {
      //Hero Bikes
      id: "Hero1",
      img: "assets/images/Splendor-Pro.jpg",
      name: "Splendor Pro",
      brand: "Hero",
      bsversion: "BS6",
      Description: 'The Hero Splendor Pro is powered by a 97.2 cc single-cylinder,\
      air-cooled engine that produces a maximum power of 8.36PS @ 8000 rpm and maximum torque of 8.05Nm @ 5000 rpm. \
      The engine is a refined unit and as per Hero, can offer a fuel efficiency of 90 kmpl.',
      price: '47,505 - 51,476*',
      rating: 4.4,
      displacement: 97.2,
      miledge: 90,
      weight: 112,
      width: 720,
      height: 1040,
      lenght: 1970,
      frontwheelsize: 1230,
      rearwheelsize: 1230,
      wheeltype: "Aloy",
      rearbreaking: "Drum",
      frontbreaking: "Drum",
      breakingSystem: "Combo Breking",
      headlight: "LED",
      type: "Road Bike",
      colors: [
        {name: "gold", color: "gold"},
        {name: "maroon", color: "maroon"},
        {name: "grey", color: "grey"},
        {name: "silver", color: "silver"} ],
      fueltype: 'Petrol',
      cooling_sysem: "Air Cooled",
      max_power: '8.36 PS @ 8000 rpm',
      fueldeliverysystem: "",
      bodytype: "Commuter",
      fuelcapacity: 11,
      noofcylinders: 1,
      groundclearance: 159
    },
    {
      id: "Royal1",
      img: "assets/images/Enfield.jpg",
      name: "Royal Enfield Classic 350",
      brand: "Royal Enfield",
      bsversion: "BS6",
      Description: `Its mechanical simplicity and old-school motor help in giving you some fleeting moments of bliss and the “feel” of riding a RE.`,
      price: '216000',
      rating: 4.6,
      displacement: 350,
      miledge: 65,
      weight: 109,
      width: 30,
      height: 90,
      lenght: 400,
      frontwheelsize: 20,
      rearwheelsize: 20,
      wheeltype: "Aloy",
      rearbreaking: "Drum",
      frontbreaking: "Drum",
      breakingSystem: "Combo Breking",
      headlight: "LED",
      type: "Road Bike",
      colors: [{name: "black" , color: "black"}, {name: "red" , color: "red"}, {name: "blue" , color: "blue"}],
      fueltype: 'Petrol',
      cooling_sysem: "Air Cooled",
      max_power: '2.5',
      fueldeliverysystem: "",
      bodytype: "Cruisersr",
      fuelcapacity: 11,
      noofcylinders: 1,
      groundclearance: 159
    },
    {
      id: "Yamaha1",
      img: "assets/images/yamaR15.jpg",
      name: "Yamaha YZF R15 V3",
      brand: "Yamaha",
      bsversion: "BS6",
      Description: "Splendor is a perfect bike for daily use. ... This bike is lightweight, if you want a heavy bike , this bike is not for you. This bike is not suitable for long rides.",
      price: '186000',
      rating: 4.2,
      displacement: 110,
      miledge: 65,
      weight: 109,
      width: 30,
      height: 90,
      lenght: 400,
      frontwheelsize: 20,
      rearwheelsize: 20,
      wheeltype: "Aloy",
      rearbreaking: "Drum",
      frontbreaking: "Drum",
      breakingSystem: "Combo Breking",
      headlight: "LED",
      type: "Road Bike",
      colors: [{name: "black" , color: "black"}, {name: "red" , color: "red"}, {name: "blue" , color: "blue"}],
      fueltype: 'Petrol',
      cooling_sysem: "Air Cooled",
      max_power: "2.5",
      fueldeliverysystem: "",
      bodytype: "Sport",
      fuelcapacity: 11,
      noofcylinders: 1,
      groundclearance: 159
    },
    {
      id: "Suzuki1",
      img: "assets/images/gixxer.png",
      name: "Gixxer",
      brand: "Suzuki",
      bsversion: "BS6",
      Description: "Stylish Bike",
      price: "156000",
      rating: 4.7,
      displacement: 110,
      miledge: 65,
      weight: 109,
      width: 30,
      height: 90,
      lenght: 400,
      frontwheelsize: 20,
      rearwheelsize: 20,
      wheeltype: "Aloy",
      rearbreaking: "Drum",
      frontbreaking: "Drum",
      breakingSystem: "Combo Breking",
      headlight: "LED",
      type: "Road Bike",
      colors: [{name: "black" , color: "black"}, {name: "red" , color: "red"}, {name: "blue" , color: "blue"}],
      fueltype: 'Petrol',
      cooling_sysem: "Air Cooled",
      max_power: "2.5",
      fueldeliverysystem: "",
      bodytype: "Sport",
      fuelcapacity: 11,
      noofcylinders: 1,
      groundclearance: 159
    },
    {
      id: "Honda1",
      img: "assets/images/activa.jpg",
      name: "Honda Activa 6G",
      brand: "Honda",
      bsversion: "BS6",
      Description: "Honda Activa 6G is a scooter available at a price range of Rs. 67,843 to 71,089\
       in India. It is available in 4 variants and 8 colours.\
       The Activa 6G is a powered by 109cc BS6 engine.",
      price: "678423",
      rating: 4.8,
      displacement: 109.51,
      miledge: 50,
      weight: 109,
      width: 30,
      height: 90,
      lenght: 400,
      frontwheelsize: 20,
      rearwheelsize: 20,
      wheeltype: "Aloy",
      rearbreaking: "Drum",
      frontbreaking: "Drum",
      breakingSystem: "Combo Breking",
      headlight: "LED",
      type: "Road Bike",
      colors: [{name: "black" , color: "black"}, {name: "red" , color: "red"}, {name: "blue" , color: "blue"}],
      fueltype: 'Petrol',
      cooling_sysem: "Fan Cooled",
      transmission: "",
      max_power: "12",
      max_torq: "8.79",
      fueldeliverysystem: "",
      bodytype: "Scooty",
      fuelcapacity: 11,
      noofcylinders: 1,
      groundclearance: 159
    },
    {
      id: "Honda2",
      img: "assets/images/shine.png",
      name: "Honda Shine",
      brand: "Honda",
      bsversion: "BS6",
      Description: "Super Cool scooter",
      price: 67922,
      rating: 4.3,
      displacement: 125.51,
      miledge: 60,
      weight: 125,
      width: 30,
      height: 90,
      lenght: 400,
      frontwheelsize: 20,
      rearwheelsize: 20,
      wheeltype: "Aloy",
      rearbreaking: "Drum",
      frontbreaking: "Drum",
      breakingSystem: "Combo Breking",
      headlight: "LED",
      type: "Road Bike",
      colors: [{name: "black" , color: "black"}, {name: "red" , color: "red"}, {name: "blue" , color: "blue"}],
      fueltype: 'Petrol',
      cooling_sysem: "Fan Cooled",
      transmission: "",
      max_power: 7.6,
      max_torq: 8.79,
      fueldeliverysystem: "",
      bodytype: "Commuter",
      fuelcapacity: 11,
      noofcylinders: 1,
      groundclearance: 159
    },
    {
      id: "Honda3",
      img: "assets/images/brand/honda/grazzia.png",
      name: "Grazziya",
      brand: "Honda",
      bsversion: "BS6",
      Description: "The Honda Grazia is a modern and stylish 125cc scooter for those who want something jazzier than the Activa 125.",
      price: 79952,
      rating: 4.1,
      displacement: 125.51,
      miledge: 50,
      weight: 116,
      width: 130,
      height: 290,
      lenght: 1800,
      frontwheelsize: 20,
      rearwheelsize: 20,
      wheeltype: "Aloy",
      rearbreaking: "Drum",
      frontbreaking: "Disc",
      breakingSystem: "Combo Breking",
      headlight: "LED",
      type: "Road Bike",
      colors: [{name: "gold" , color: "gold"}, {name: "red" , color: "red"}, {name: "black" , color: "black"}],
      fueltype: 'Petrol',
      cooling_sysem: "Fan Cooled",
      transmission: "Automatic",
      max_power: 7.6,
      max_torq: 8.79,
      fueldeliverysystem: "Fuel Enjection",
      bodytype: "Commuter",
      fuelcapacity: 5.3,
      noofcylinders: 1,
      groundclearance: 159
    },
    {
      id: "Honda4",
      img: "assets/images/brand/honda/Unicorn.png",
      name: "Unicorn",
      brand: "Honda",
      bsversion: "BS6",
      Description: "Honda takes forward its philosophy to the next level with the Unicorn BS-VI that prides itself on the perfect blend of quality, comfort and class.",
      price: 79952,
      rating: 4.1,
      displacement: 125.51,
      miledge: 50,
      weight: 116,
      width: 130,
      height: 290,
      lenght: 1800,
      frontwheelsize: 20,
      rearwheelsize: 20,
      wheeltype: "Aloy",
      rearbreaking: "Drum",
      frontbreaking: "Disc",
      breakingSystem: "Combo Breking",
      headlight: "LED",
      type: "Road Bike",
      colors: [{name: "red" , color: "red"}, {name: "black" , color: "black"}],
      fueltype: 'Petrol',
      cooling_sysem: "Fan Cooled",
      transmission: "Automatic",
      max_power: 7.6,
      max_torq: 8.79,
      fueldeliverysystem: "Fuel Enjection",
      bodytype: "Commuter",
      fuelcapacity: 5.3,
      noofcylinders: 1,
      groundclearance: 159
    },
    {
      id: "TVS1",
      img: "assets/images/brand/TVS/apache.png",
      name: "Apache",
      brand: "TVS",
      bsversion: "BS6",
      Description: "Honda takes forward its philosophy to the next level with the Unicorn BS-VI that prides itself on the perfect blend of quality, comfort and class.",
      price: 179952,
      rating: 4.3,
      displacement: 150.51,
      miledge: 35,
      weight: 136,
      width: 130,
      height: 290,
      lenght: 1800,
      frontwheelsize: 120,
      rearwheelsize: 120,
      wheeltype: "Aloy",
      rearbreaking: "Disc",
      frontbreaking: "Disc",
      breakingSystem: "ABS",
      headlight: "LED",
      type: "Road Bike",
      colors: [ {name: "yellow" , color: "yellow"}, {name: "yellow" , color: "yellow"}],
      fueltype: 'Petrol',
      cooling_sysem: "Fan Cooled",
      transmission: "Manual 5Gear",
      max_power: 11.6,
      max_torq: 10.79,
      fueldeliverysystem: "Fuel Enjection",
      bodytype: "Commuter",
      fuelcapacity: 5.3,
      noofcylinders: 1,
      groundclearance: 159
    },
    {
      id: "TVS2",
      img: "assets/images/brand/TVS/jupiter.png",
      name: "Jupiter",
      brand: "TVS",
      bsversion: "BS6",
      Description: "TVS Jupiter is a variomatic scooter launched in September 2013 by India's TVS Motor Company. The launch of the scooter marked the company's entry into the part of the market that mainly targets females. It is powered by a single-cylinder, four-stroke, 110 cc engine and delivers 5.88 kW at 7,500 rpm. ",
      price: 69952,
      rating: 4.8,
      displacement: 110.51,
      miledge: 55,
      weight: 106,
      width: 130,
      height: 290,
      lenght: 1800,
      frontwheelsize: 110,
      rearwheelsize: 110,
      wheeltype: "Aloy",
      rearbreaking: "Drum",
      frontbreaking: "Drum",
      breakingSystem: "Combo Breking",
      headlight: "LED",
      type: "Scooty",
      colors: [{name: "red" , color: "red"}, {name: "blue" , color: "blue"}, {name: "yellow" , color: "yellow"}, {name: "white" , color: "white"}, {name: "black" , color: "black"}],
      fueltype: 'Petrol',
      cooling_sysem: "Air Cooled",
      transmission: "Automatic",
      max_power: 8.6,
      max_torq: 5.79,
      fueldeliverysystem: "Fuel Enjection",
      bodytype: "Scooty",
      fuelcapacity: 5.3,
      noofcylinders: 1,
      groundclearance: 159
    },
  ]