import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-card',
  templateUrl: './card.component.html',
  template: `
    <app-bike [childMessage]=bike></app-bike>
  `,
  styleUrls: ['./card.component.css']
})
export class CardComponent implements OnInit {
  bike = [
    {
      b_id: "Hero1",
      b_img: "assets/images/Splendor-Pro.jpg",
      b_name: "Splendor Pro",
      b_brand: "Hero",
      b_bsversion: "BS6",
      b_Description: '',
      b_price: 56000,
      b_rating: 4.4,
      b_displacement: 110,
      b_miledge: 65,
      b_weight: 109,
      b_width: 30,
      b_height: 90,
      b_lenght: 400,
      b_frontwheelsize: 20,
      b_rearwheelsize: 20,
      b_wheeltype: "Aloy",
      b_breaking: "Disk Break",
      b_breakingSystem: "Combo Breking",
      b_headlight: "LED",
      b_type: "Road Bike",
      b_colors: ["black", "red", "blue"],
      b_about: `Splendor is a perfect bike for daily use.
      This bike is lightweight, if you want a heavy bike , 
      this bike is not for you. This bike is not suitable for long rides.`,
      b_fueltype: 'Petrol',
      b_cooling_sysem: "",
      b_max_power: 2.5,
      b_fueldeliverysystem: ""
    },

    {
      b_id: "Royal1",
      b_img: "assets/images/Enfield.jpg",
      b_name: "Royal Enfield Classic 350",
      b_brand: "Royal Enfield",
      b_bsversion: "BS6",
      b_Description: `Its mechanical simplicity and old-school motor help in giving you some fleeting moments of bliss and the “feel” of riding a RE.`,
      b_price: 216000,
      b_rating: 4.6,
      b_displacement: 350,
      b_miledge: 65,
      b_weight: 109,
      b_width: 30,
      b_height: 90,
      b_lenght: 400,
      b_frontwheelsize: 20,
      b_rearwheelsize: 20,
      b_wheeltype: "Aloy",
      b_breaking: "Disk Break",
      b_breakingSystem: "Combo Breking",
      b_headlight: "LED",
      b_type: "Road Bike",
      b_colors: ["black", "red", "blue"],
      b_about: `Splendor is a perfect bike for daily use.
      This bike is lightweight, if you want a heavy bike , 
      this bike is not for you. This bike is not suitable for long rides.`,
      b_fueltype: 'Petrol',
      b_cooling_sysem: "",
      b_max_power: 2.5,
      b_fueldeliverysystem: ""
    },

    {
      b_id: "Yamaha1",
      b_img: "assets/images/yamaR15.jpg",
      b_name: "Yamaha YZF R15 V3",
      b_brand: "Yamaha",
      b_bsversion: "BS6",
      b_Description: "Splendor is a perfect bike for daily use. ... This bike is lightweight, if you want a heavy bike , this bike is not for you. This bike is not suitable for long rides.",
      b_price: 186000,
      b_rating: 4.2,
      b_displacement: 110,
      b_miledge: 65,
      b_weight: 109,
      b_width: 30,
      b_height: 90,
      b_lenght: 400,
      b_frontwheelsize: 20,
      b_rearwheelsize: 20,
      b_wheeltype: "Aloy",
      b_breaking: "Disk Break",
      b_breakingSystem: "Combo Breking",
      b_headlight: "LED",
      b_type: "Road Bike",
      b_colors: ["black", "red", "blue"],
      b_about: `Splendor is a perfect bike for daily use.
      This bike is lightweight, if you want a heavy bike , 
      this bike is not for you. This bike is not suitable for long rides.`,
      b_fueltype: 'Petrol',
      b_cooling_sysem: "",
      b_max_power: 2.5,
      b_fueldeliverysystem: ""
    },
    {
      b_id: "Suzuki1",
      b_img: "assets/images/gixxer.png",
      b_name: "Gixxer",
      b_brand: "Suzuki",
      b_bsversion: "BS6",
      b_Description: "Stylish Bike",
      b_price: 156000,
      b_rating: 4.7,
      b_displacement: 110,
      b_miledge: 65,
      b_weight: 109,
      b_width: 30,
      b_height: 90,
      b_lenght: 400,
      b_frontwheelsize: 20,
      b_rearwheelsize: 20,
      b_wheeltype: "Aloy",
      b_breaking: "Disk Break",
      b_breakingSystem: "Combo Breking",
      b_headlight: "LED",
      b_type: "Road Bike",
      b_colors: ["black", "red", "blue"],
      b_about: `Splendor is a perfect bike for daily use.
      This bike is lightweight, if you want a heavy bike , 
      this bike is not for you. This bike is not suitable for long rides.`,
      b_fueltype: 'Petrol',
      b_cooling_sysem: "",
      b_max_power: 2.5,
      b_fueldeliverysystem: ""
    },
    {
      b_id: "Honda1",
      b_img: "assets/images/activa.jpg",
      b_name: "Honda Activa 6G",
      b_brand: "Honda",
      b_bsversion: "BS6",
      b_Description: "Super Cool scooter",
      b_price: 67922,
      b_rating: 4.8,
      b_displacement: 109.51,
      b_miledge: 50,
      b_weight: 109,
      b_width: 30,
      b_height: 90,
      b_lenght: 400,
      b_frontwheelsize: 20,
      b_rearwheelsize: 20,
      b_wheeltype: "Aloy",
      b_breaking: "Disk Break",
      b_breakingSystem: "Combo Breking",
      b_headlight: "LED",
      b_type: "Road Bike",
      b_colors: ["black", "red", "blue"],
      b_about: `Splendor is a perfect bike for daily use.
      This bike is lightweight, if you want a heavy bike , 
      this bike is not for you. This bike is not suitable for long rides.`,
      b_fueltype: 'Petrol',
      b_cooling_sysem: "Fan Cooled",
      b_transmission: "",
      b_max_power: 0,
      b_max_torq: 8.79,
      b_fueldeliverysystem: ""
    },
    {
      b_id: "Honda2",
      b_img: "assets/images/shine.png",
      b_name: "Honda Shine",
      b_brand: "Honda",
      b_bsversion: "BS6",
      b_description: "Super Cool scooter",
      b_price: 67922,
      b_rating: 4.3,
      b_displacement: 125.51,
      b_miledge: 60,
      b_weight: 125,
      b_width: 30,
      b_height: 90,
      b_lenght: 400,
      b_frontwheelsize: 20,
      b_rearwheelsize: 20,
      b_wheeltype: "Aloy",
      b_breaking: "Disk Break",
      b_breakingSystem: "Combo Breking",
      b_headlight: "LED",
      b_type: "Road Bike",
      b_colors: ["black", "red", "blue"],
      b_about: `Splendor is a perfect bike for daily use.
      This bike is lightweight, if you want a heavy bike , 
      this bike is not for you. This bike is not suitable for long rides.`,
      b_fueltype: 'Petrol',
      b_cooling_sysem: "Fan Cooled",
      b_transmission: "",
      b_max_power: 7.6,
      b_max_torq: 8.79,
      b_fueldeliverysystem: ""
    }
  ]

  constructor() { }

  ngOnInit(): void {
  }

}
